/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.UserController;
import Model.User;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author MyPC
 */
public class LoginFrame extends javax.swing.JFrame {

  private MainFrame mf;
    
  public LoginFrame(MainFrame mf) {
        this.mf = mf;
        initComponents();
    }
    
    
    /** Creates new form LoginFrame */
    public LoginFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_lg_username = new javax.swing.JTextField();
        bnt_xacnhan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lb_lg_register = new javax.swing.JLabel();
        txt_lg_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên tài khoản");
        jLabel1.setPreferredSize(new java.awt.Dimension(6, 14));

        jLabel2.setText("Mật khẩu");
        jLabel2.setPreferredSize(new java.awt.Dimension(6, 14));

        txt_lg_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lg_usernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lg_usernameKeyTyped(evt);
            }
        });

        bnt_xacnhan.setText("Xác nhận");
        bnt_xacnhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_xacnhanMouseClicked(evt);
            }
        });

        jButton2.setText("Thoát");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        lb_lg_register.setText("Đăng kí tài khoản mới");
        lb_lg_register.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_lg_registerMouseMoved(evt);
            }
        });
        lb_lg_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_lg_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_lg_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_lg_registerMouseExited(evt);
            }
        });

        txt_lg_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lg_passwordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lg_passwordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_lg_username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnt_xacnhan)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(txt_lg_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_lg_register)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_lg_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_lg_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(bnt_xacnhan))
                .addGap(45, 45, 45)
                .addComponent(lb_lg_register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_lg_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lg_registerMouseClicked
        RegisterFrame rf = new RegisterFrame();
        rf.setVisible(true);
    }//GEN-LAST:event_lb_lg_registerMouseClicked

    private void bnt_xacnhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_xacnhanMouseClicked
        if(this.checkLogin()){
            mf.setUser_sudung(this.getUser());
            mf.DangNhap();
            mf.loadListPostChoThue();
            mf.loadTinCuaBan();
           this.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(null, "Kiểm tra lại tài khoản hoặc mật khẩu!");
           
    }//GEN-LAST:event_bnt_xacnhanMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void lb_lg_registerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lg_registerMouseMoved
        this.lb_lg_register.setCursor(new Cursor(Cursor.HAND_CURSOR));    
    }//GEN-LAST:event_lb_lg_registerMouseMoved

    private void lb_lg_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lg_registerMouseEntered
       
    }//GEN-LAST:event_lb_lg_registerMouseEntered

    private void lb_lg_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lg_registerMouseExited
        
    }//GEN-LAST:event_lb_lg_registerMouseExited

    private void txt_lg_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lg_usernameKeyPressed
            
        char[] number = {' ','-','=','+','`','~','!','@','#','$','$','%','^','&','*'};  
        for(int i=0; i<number.length;i++)
        {
            if(evt.getKeyChar() == number[i])
                evt.consume();
        }
    }//GEN-LAST:event_txt_lg_usernameKeyPressed

    private void txt_lg_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lg_passwordKeyPressed
          char[] number = {' ','-','=','+','`','~','!','@','#','$','$','%','^','&','*'};  
        for(int i=0; i<number.length;i++)
        {
            if(evt.getKeyChar() == number[i])
                evt.consume();
        }
    }//GEN-LAST:event_txt_lg_passwordKeyPressed

    private void txt_lg_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lg_usernameKeyTyped
              char[] number = {' ','-','=','+','`','~','!','@','#','$','$','%','^','&','*'};  
        for(int i=0; i<number.length;i++)
        {
            if(evt.getKeyChar() == number[i])
                evt.consume();
        }
    }//GEN-LAST:event_txt_lg_usernameKeyTyped

    private void txt_lg_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lg_passwordKeyTyped
              char[] number = {' ','-','=','+','`','~','!','@','#','$','$','%','^','&','*'};  
        for(int i=0; i<number.length;i++)
        {
            if(evt.getKeyChar() == number[i])
                evt.consume();
        }
    }//GEN-LAST:event_txt_lg_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    public boolean checkLogin(){
        
        UserController uc =new  UserController();
        ArrayList<User> list = uc.getUser();
        String username = txt_lg_username.getText();
        String password = txt_lg_password.getText();
       
        
        for(int i=0;i<list.size();i++){
            if(list.get(i).getUsername().equals(username)){
                if(list.get(i).getPassword().equals(password)){
                    return true;
                }
            }
        }
        return false;
    }
    
    public User getUser(){
        UserController uc = new UserController();
        String username = txt_lg_username.getText();
        String password = txt_lg_password.getText();

        ArrayList<User> list = uc.getUser();
        for(int i=0;i<list.size();i++)
            if(list.get(i).getUsername().equals(username) && list.get(i).getPassword().equals(password))
                return list.get(i);
                
        return null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_xacnhan;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_lg_register;
    private javax.swing.JPasswordField txt_lg_password;
    private javax.swing.JTextField txt_lg_username;
    // End of variables declaration//GEN-END:variables

}
