/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ConvertMoneyVN;
import Controller.PostController;
import Controller.UserController;
import Model.Post;
import Model.User;
import java.awt.Cursor;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.nio.file.Files;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MyPC
 */
public class NewPostFrame extends javax.swing.JFrame {

   private String img_cover;
   private String img1;
   private String img2;
   private String img3;
   private String img4;
   
   private User user_sudung;

    public User getUser_sudung() {
        return user_sudung;
    }
    public void setUser_sudung(User user_sudung) {
        this.user_sudung = user_sudung;
    }
  
    private MainFrame mf;
    private Post post;

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
    }
    
    public NewPostFrame(User user,MainFrame mf) {
        initComponents();
        this.user_sudung = user;
        this.mf =mf;
        this.bnt_XacNhan.setVisible(false);
    }
    
       public NewPostFrame(User user,MainFrame mf,Post post) {
        initComponents();
        this.user_sudung = user;
        this.mf =mf;
        this.post = post;
        this.bnt_dangtin.setVisible(false);
        loadPost();
    }
     public void loadPost()
     {
         if(post.getKind().equals("chothue"))
             this.rbnt_chothue.setSelected(true);
         else 
             this.rbnt_canthue.setSelected(true);
         this.txt_title.setText(post.getTitle());
         this.txt_price.setText(String.valueOf(post.getPrice()));
         this.txt_detail.setText(post.getDetail());
         this.txt_adress_post.setText(post.getAdress_post());
         this.cbbQuan.setSelectedItem(post.getQuan());
         this.txt_area.setText(post.getArea());
         this.txt_contact.setText(post.getContact());
         
        
        
        ImageIcon icon_cover = new ImageIcon(new ImageIcon(post.getImg_cover()).getImage().getScaledInstance(220, 220, Image.SCALE_SMOOTH));        
        this.lb_img_cover.setIcon(icon_cover);
        this.lb_img_cover.setText(null);
        
        ImageIcon icon1 = new ImageIcon(new ImageIcon(post.getImg1()).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));        
        this.lb_img1.setIcon(icon1);
        this.lb_img1.setText(null);
        ImageIcon icon2 = new ImageIcon(new ImageIcon(post.getImg2()).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));        
        this.lb_img2.setIcon(icon2);
        this.lb_img2.setText(null);
        ImageIcon icon3 = new ImageIcon(new ImageIcon(post.getImg3()).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));        
        this.lb_img3.setIcon(icon3);
        this.lb_img3.setText(null);
        ImageIcon icon4 = new ImageIcon(new ImageIcon(post.getImg4()).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));        
        this.lb_img4.setIcon(icon4);
        this.lb_img4.setText(null);
        
        
        
         
     }
       
       
    /**
     * Creates new form NewPostFrame
     */
    public NewPostFrame() {
        initComponents();
    }

     public NewPostFrame(MainFrame mf) {
        initComponents();
        this.mf = mf;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_area = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_detail = new javax.swing.JTextArea();
        txt_title = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_adress_post = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbnt_canthue = new javax.swing.JRadioButton();
        rbnt_chothue = new javax.swing.JRadioButton();
        lb_img_cover = new javax.swing.JLabel();
        lb_img4 = new javax.swing.JLabel();
        lb_img2 = new javax.swing.JLabel();
        lb_img1 = new javax.swing.JLabel();
        lb_img3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bnt_dangtin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbbQuan = new javax.swing.JComboBox<>();
        bnt_XacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tiêu đề");

        txt_contact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contactKeyTyped(evt);
            }
        });

        jLabel2.setText("Giá cho thuê");

        jLabel3.setText("Diện tích phòng");

        txt_price.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_priceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_priceKeyTyped(evt);
            }
        });

        jLabel4.setText("Địa chỉ phòng");

        txt_area.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_area.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_areaKeyTyped(evt);
            }
        });

        jLabel5.setText("Thông tin thêm");

        txt_detail.setColumns(20);
        txt_detail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_detail.setRows(5);
        jScrollPane1.setViewportView(txt_detail);

        txt_title.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setText("Sđt liên hệ");

        txt_adress_post.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup1.add(rbnt_canthue);
        rbnt_canthue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbnt_canthue.setText("Cần thuê");

        buttonGroup1.add(rbnt_chothue);
        rbnt_chothue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbnt_chothue.setText("Cho thuê");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbnt_chothue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(rbnt_canthue)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnt_chothue)
                    .addComponent(rbnt_canthue))
                .addContainerGap())
        );

        lb_img_cover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img_cover.setText("Chọn ảnh đại diện");
        lb_img_cover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb_img_cover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_img_coverMouseMoved(evt);
            }
        });
        lb_img_cover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_img_coverMouseClicked(evt);
            }
        });

        lb_img4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img4.setText("Ảnh 4");
        lb_img4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb_img4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_img4MouseMoved(evt);
            }
        });
        lb_img4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_img4MouseClicked(evt);
            }
        });

        lb_img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img2.setText("Ảnh 2");
        lb_img2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb_img2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_img2MouseMoved(evt);
            }
        });
        lb_img2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_img2MouseClicked(evt);
            }
        });

        lb_img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img1.setText("Ảnh 1");
        lb_img1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb_img1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_img1MouseMoved(evt);
            }
        });
        lb_img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_img1MouseClicked(evt);
            }
        });

        lb_img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img3.setText("Ảnh 3");
        lb_img3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb_img3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_img3MouseMoved(evt);
            }
        });
        lb_img3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_img3MouseClicked(evt);
            }
        });

        jLabel12.setText("m vuông");

        jLabel13.setText("đồng /tháng");

        jButton1.setText("Thoát");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton1MouseDragged(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        bnt_dangtin.setText("Đăng tin");
        bnt_dangtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_dangtinMouseClicked(evt);
            }
        });

        jLabel7.setText("Quận");

        cbbQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Quận 1", "Quận 2", "Quận 3", "Quận 4", "Quận 5", "Quận 6", "Quận 7", "Quận 8", "Quận 9", "Quận 10", "Quận 11", "Quận 12", "Quận Thủ Đức", "Quận Bình Thạnh", "Quận Gò Vấp", "Quận Phú Nhuận", "Quận Tân Phú", "Quận Bình Tân", "Quận Tân Bình", "Huyện Nhà Bè", "Huyện Bình Chánh", "Huyện Hóc Môn", "Huyện Củ Chi", "Huyện Cần Giờ" }));
        cbbQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbQuanActionPerformed(evt);
            }
        });

        bnt_XacNhan.setText("Xác nhận");
        bnt_XacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_XacNhanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnt_dangtin)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_img_cover, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_img3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_img2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_img4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnt_XacNhan))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(52, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_adress_post, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_adress_post, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_img_cover, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_img2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_img4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_img3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt_dangtin)
                    .addComponent(bnt_XacNhan))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseDragged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void bnt_dangtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_dangtinMouseClicked
        switch(this.checkInput()){
            case 0:{
                this.LuuBaiDang();
                JOptionPane.showMessageDialog(null, "Đăng bài thành công!");
                this.setVisible(false);
                mf.loadListPostChoThue();
                mf.loadTinCuaBan();
                break;
            }
            case 1:{
                JOptionPane.showMessageDialog(null, "Chưa chọn loại tin cần đăng!");
                break;
            }
            case 2:{
                JOptionPane.showMessageDialog(null, "Cần điền tiêu đề bài đăng!");
                break;
            }
            case 3:{
                JOptionPane.showMessageDialog(null, "Cần cho biết giá cho/cần thuê!");
                break;
            }
            case 4:{
                JOptionPane.showMessageDialog(null, "Cần cho biết địa điểm cho/cần thuê!");
                break;
            }
            case 5:{
                JOptionPane.showMessageDialog(null, "Cần cho biết số điện thoại liên hệ!");
                break;
            }
            case 6:{
                JOptionPane.showMessageDialog(null, "Cần cho biết phòng cho/cần thuê nằm ở quận nào!");
                break;
            }
            default:{
               break;
            }
                
        }
    }//GEN-LAST:event_bnt_dangtinMouseClicked

    private void lb_img_coverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img_coverMouseClicked
        String fileName = null;
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        fileName = f.getAbsolutePath();
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(220, 220, Image.SCALE_SMOOTH));
        lb_img_cover.setIcon(imageIcon);  
        lb_img_cover.setText(null);
        img_cover = fileName;
        this.post.setImg_cover(this.LoadImg(img_cover));
    }//GEN-LAST:event_lb_img_coverMouseClicked

    private void lb_img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img1MouseClicked
          String fileName = null;
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        fileName = f.getAbsolutePath();
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        lb_img1.setIcon(imageIcon);  
        lb_img1.setText(null);
        img1 = fileName;
        this.post.setImg1(this.LoadImg(img1));
    }//GEN-LAST:event_lb_img1MouseClicked

    private void lb_img2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img2MouseClicked
        String fileName = null;
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        fileName = f.getAbsolutePath();
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        lb_img2.setIcon(imageIcon);  
        lb_img2.setText(null);
        img2 = fileName;
        this.post.setImg2(this.LoadImg(img2));
    }//GEN-LAST:event_lb_img2MouseClicked

    private void lb_img3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img3MouseClicked
        String fileName = null;
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        fileName = f.getAbsolutePath();
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        lb_img3.setIcon(imageIcon);  
        lb_img3.setText(null);
        img3 = fileName;
        this.post.setImg3(this.LoadImg(img3));
    }//GEN-LAST:event_lb_img3MouseClicked

    private void lb_img4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img4MouseClicked
        String fileName = null;
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        fileName = f.getAbsolutePath();
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        lb_img4.setIcon(imageIcon);  
        lb_img4.setText(null);
        img4 = fileName;
        this.post.setImg4(this.LoadImg(img4));
    }//GEN-LAST:event_lb_img4MouseClicked

    private void lb_img_coverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img_coverMouseMoved
         this.lb_img_cover.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_lb_img_coverMouseMoved

    private void lb_img1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img1MouseMoved
        this.lb_img1.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_lb_img1MouseMoved

    private void lb_img2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img2MouseMoved
        this.lb_img2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lb_img2MouseMoved

    private void lb_img3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img3MouseMoved
       this.lb_img3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lb_img3MouseMoved

    private void lb_img4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_img4MouseMoved
        this.lb_img4.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lb_img4MouseMoved

    private void cbbQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbQuanActionPerformed

    private void txt_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyTyped
        boolean check = false;
        char[] number = {'0','1','2','3','4','5','6','7','8','9'};  
        for(int i = 0;i<number.length;i++)
            if(evt.getKeyChar() == number[i] )
            {
                check = true;
                break;
            }
        if(check == false)
          evt.consume();  
    }//GEN-LAST:event_txt_priceKeyTyped

    private void txt_areaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_areaKeyTyped
         boolean check = false;
        char[] number = {'0','1','2','3','4','5','6','7','8','9',','};  
        for(int i = 0;i<number.length;i++)
            if(evt.getKeyChar() == number[i] )
            {
                check = true;
                break;
            }
        if(check == false)
          evt.consume();  
    }//GEN-LAST:event_txt_areaKeyTyped

    private void txt_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyTyped
       boolean check = false;
        char[] number = {'0','1','2','3','4','5','6','7','8','9'};  
        for(int i = 0;i<number.length;i++)
            if(evt.getKeyChar() == number[i] )
            {
                check = true;
                break;
            }
        if(check == false)
          evt.consume();  
    }//GEN-LAST:event_txt_contactKeyTyped

    private void txt_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyPressed
  
    }//GEN-LAST:event_txt_priceKeyPressed

    private void bnt_XacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_XacNhanMouseClicked
       switch(this.checkInput()){
            case 0:{
                this.SuaBaiDang();
                JOptionPane.showMessageDialog(null, "Sửa bài thành công!");
                this.setVisible(false);
                mf.loadListPostChoThue();
                mf.loadTinCuaBan();
                break;
            }
            case 1:{
                JOptionPane.showMessageDialog(null, "Chưa chọn loại tin cần đăng!");
                break;
            }
            case 2:{
                JOptionPane.showMessageDialog(null, "Cần điền tiêu đề bài đăng!");
                break;
            }
            case 3:{
                JOptionPane.showMessageDialog(null, "Cần cho biết giá cho/cần thuê!");
                break;
            }
            case 4:{
                JOptionPane.showMessageDialog(null, "Cần cho biết địa điểm cho/cần thuê!");
                break;
            }
            case 5:{
                JOptionPane.showMessageDialog(null, "Cần cho biết số điện thoại liên hệ!");
                break;
            }
            case 6:{
                JOptionPane.showMessageDialog(null, "Cần cho biết phòng cho/cần thuê nằm ở quận nào!");
                break;
            }
            default:{
               break;
            }
                
        }
    }//GEN-LAST:event_bnt_XacNhanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPostFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPostFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPostFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPostFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPostFrame().setVisible(true);
            }
        });
    }

    public int checkInput(){
    
        if(rbnt_canthue.isSelected()== false && rbnt_chothue.isSelected()== false )
            return 1;
        else{
            if(txt_title.getText().equals(""))
                return 2;
            else{
                if(txt_price.getText().equals(""))
                    return 3;
                else{
                    if(txt_adress_post.getText().equals(""))
                        return 4;
                    else{
                        if(txt_contact.getText().equals(""))
                            return 5;
                        else 
                            if(cbbQuan.getSelectedItem().toString().equals("--Select--"))
                                return 6;
                    }
                }
            }
        }
        
        return 0;
    }
     public void SuaBaiDang(){
        
        
        post.setTitle(txt_title.getText());
        post.setPrice(parseInt(txt_price.getText()));
        if(txt_area.getText().equals(""))
            post.setArea("Chưa biết");
        else
            post.setArea(txt_area.getText());
        post.setAdress_post(txt_adress_post.getText());
        
        if(rbnt_chothue.isSelected())
            post.setKind("chothue");
        else 
            post.setKind("canthue");
        
        post.setContact(txt_contact.getText());
        post.setDetail(txt_detail.getText());
        post.setStatus("co hieu luc");
        
        post.setId_user(user_sudung.getId_user());
        
    
        
        
        post.setDop_post(this.post.getDop_post());
        
        post.setQuan(cbbQuan.getSelectedItem().toString());
        
        PostController pc = new PostController();
        pc.updatePost(post);
    }
    
    
    
    public void LuuBaiDang(){
        Post post = new Post();
        
        post.setTitle(txt_title.getText());
        post.setPrice(parseInt(txt_price.getText()));
        if(txt_area.getText().equals(""))
            post.setArea("Chưa biết");
        else
            post.setArea(txt_area.getText());
        post.setAdress_post(txt_adress_post.getText());
        
        if(rbnt_chothue.isSelected())
            post.setKind("chothue");
        else 
            post.setKind("canthue");
        
        post.setContact(txt_contact.getText());
        post.setDetail(txt_detail.getText());
        post.setStatus("co hieu luc");
        
        post.setId_user(user_sudung.getId_user());
        
        post.setImg_cover(this.LoadImg(img_cover));
        post.setImg1(this.LoadImg(img1));
        post.setImg2(this.LoadImg(img2));
        post.setImg3(this.LoadImg(img3));
        post.setImg4(this.LoadImg(img4));
        
        Calendar date = Calendar.getInstance();
        post.setDop_post(date);
        
        post.setQuan(cbbQuan.getSelectedItem().toString());
        
        PostController pc = new PostController();
        pc.insertPost(post);
    }
    
    public byte[] LoadImg(String path){
         
        if(path != null)
        {
            try {
                File fi = new File(path);       
                byte[] file = Files.readAllBytes(fi.toPath());
                return file;
            } catch (IOException ex) {
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            
            try {
                File fi = new File("no_img.jpg");       
                byte[] file = Files.readAllBytes(fi.toPath());
                return file;
            } catch (IOException ex) {
                Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
        return null;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_XacNhan;
    private javax.swing.JButton bnt_dangtin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbQuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_img1;
    private javax.swing.JLabel lb_img2;
    private javax.swing.JLabel lb_img3;
    private javax.swing.JLabel lb_img4;
    private javax.swing.JLabel lb_img_cover;
    private javax.swing.JRadioButton rbnt_canthue;
    private javax.swing.JRadioButton rbnt_chothue;
    private javax.swing.JTextField txt_adress_post;
    private javax.swing.JTextField txt_area;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextArea txt_detail;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_title;
    // End of variables declaration//GEN-END:variables
}
