/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UserController;
import Model.DBManager;
import Model.User;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import static java.lang.Float.parseFloat;
import java.nio.file.Files;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author MyPC
 */
public class RegisterFrame extends javax.swing.JFrame {

   private MainFrame mf ;
   private User user_chon; 
    /**
     * Creates new form LoginFrame
     */
    public RegisterFrame() {
        initComponents();
        this.bntSua.setVisible(false);
    }
    
     public RegisterFrame(MainFrame mf, User user) {
        initComponents();
        this.mf = mf;
        this.user_chon = user;
        this.loadUser(user);
    }

    public void loadUser(User user){
        this.bnt_rgt_xacnhan.setVisible(false);
         this.bntSua.setVisible(true);
        this.txt_rgt_username.setEditable(false);
        
        this.txt_rgt_username.setText(user.getUsername());
        this.txtpass_rgt_password.setText(user.getPassword());
        txt_rgt_fullname.setText(user.getFullname());
        txt_rgt_email.setText(user.getEmail());
        txt_rgt_phone.setText(user.getPhone());
        txt_rgt_adress.setText(user.getAdress_user());
        
        ImageIcon img = new ImageIcon(new ImageIcon(user.getImg()).getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH));        
        this.lb_rgt_img.setIcon(img);
        this.lb_rgt_img.setText("");
    }
     
    private String path = null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_rgt_username = new javax.swing.JTextField();
        txtpass_rgt_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bnt_rgt_xacnhan = new javax.swing.JButton();
        bnt_rgt_thoat = new javax.swing.JButton();
        lb_rgt_img = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bnt_rgt_choose_img = new javax.swing.JButton();
        txt_rgt_email = new javax.swing.JTextField();
        txt_rgt_phone = new javax.swing.JTextField();
        txt_rgt_adress = new javax.swing.JTextField();
        txt_rgt_fullname = new javax.swing.JTextField();
        bntSua = new javax.swing.JButton();

        setTitle("Đăng kí tài khoản");

        txt_rgt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rgt_usernameKeyTyped(evt);
            }
        });

        txtpass_rgt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpass_rgt_passwordKeyTyped(evt);
            }
        });

        jLabel1.setText("Tên tài khoản");
        jLabel1.setPreferredSize(new java.awt.Dimension(6, 14));

        jLabel2.setText("Mật khẩu");

        bnt_rgt_xacnhan.setText("Xác nhận");
        bnt_rgt_xacnhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_rgt_xacnhanMouseClicked(evt);
            }
        });
        bnt_rgt_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_rgt_xacnhanActionPerformed(evt);
            }
        });

        bnt_rgt_thoat.setText("Thoát");
        bnt_rgt_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_rgt_thoatMouseClicked(evt);
            }
        });

        lb_rgt_img.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_rgt_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_rgt_img.setText("Ảnh đại diện");

        jLabel6.setText("Tên hiển thị");

        jLabel7.setText("Email");

        jLabel9.setText("Địa chỉ");

        jLabel10.setText("Số điện thoại");

        bnt_rgt_choose_img.setText("Chọn ảnh");
        bnt_rgt_choose_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_rgt_choose_imgMouseClicked(evt);
            }
        });

        txt_rgt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rgt_phoneKeyTyped(evt);
            }
        });

        bntSua.setText("Sửa");
        bntSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntSuaMouseClicked(evt);
            }
        });
        bntSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_rgt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lb_rgt_img, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bnt_rgt_choose_img))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(bnt_rgt_xacnhan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bntSua)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bnt_rgt_thoat))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpass_rgt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_rgt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_rgt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_rgt_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_rgt_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_rgt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpass_rgt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rgt_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rgt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rgt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rgt_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_rgt_img, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt_rgt_choose_img))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_rgt_xacnhan)
                    .addComponent(bnt_rgt_thoat)
                    .addComponent(bntSua))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_rgt_xacnhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_rgt_xacnhanMouseClicked
        boolean check = this.checkInputRegister();

        if(check ==false)
            JOptionPane.showMessageDialog(null, "Nhập thiếu dữ liệu! Vui lòng xem lại!");
        else{
            if(this.checkUser())
            {
                User user = new User();
                user.setId_user(-1);
                user.setUsername(txt_rgt_username.getText());
                user.setPassword(txtpass_rgt_password.getText());
                user.setFullname(txt_rgt_fullname.getText());
                user.setAdress_user(txt_rgt_adress.getText());
                user.setPhone(txt_rgt_phone.getText());
                user.setEmail(txt_rgt_email.getText());
                
                Calendar date = Calendar.getInstance();
                user.setDop_user(date);
                user.setImg(LoadImg(path));
                
                UserController ctr = new UserController();
                ctr.insertUser(user);
                JOptionPane.showMessageDialog(null, "Đăng kí thành công!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Tên đăng nhập đã tồn tại! Vui lòng chọn tên đăng nhập khác!");
            }      
        }
         
    }//GEN-LAST:event_bnt_rgt_xacnhanMouseClicked

    private void bnt_rgt_choose_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_rgt_choose_imgMouseClicked
        String fileName = null;
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        fileName = f.getAbsolutePath();
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        lb_rgt_img.setIcon(imageIcon);  
        lb_rgt_img.setText(null);
        path = fileName;
        this.user_chon.setImg(LoadImg(path));
    }//GEN-LAST:event_bnt_rgt_choose_imgMouseClicked

        public byte[] LoadImg(String path){
         
        if(path != null)
        {
            try {
                File fi = new File(path);       
                byte[] file = Files.readAllBytes(fi.toPath());
                return file;
            } catch (IOException ex) {
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            
            try {
                File fi = new File("no_img.jpg");       
                byte[] file = Files.readAllBytes(fi.toPath());
                return file;
            } catch (IOException ex) {
                Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
        return null;
    }
    
    private void bnt_rgt_thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_rgt_thoatMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_bnt_rgt_thoatMouseClicked

    private void txt_rgt_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rgt_usernameKeyTyped
        char[] number = {' ','-','=','+','`','~','!','@','#','$','$','%','^','&','*'};  
        for(int i=0; i<number.length;i++)
        {
            if(evt.getKeyChar() == number[i])
                evt.consume();
        }
    }//GEN-LAST:event_txt_rgt_usernameKeyTyped

    private void txtpass_rgt_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpass_rgt_passwordKeyTyped
        char[] number = {' ','-','=','+','`','~','!','@','#','$','$','%','^','&','*'};  
        for(int i=0; i<number.length;i++)
        {
            if(evt.getKeyChar() == number[i])
                evt.consume();
        }
    }//GEN-LAST:event_txtpass_rgt_passwordKeyTyped

    private void txt_rgt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rgt_phoneKeyTyped
       boolean kt= false;
       char[] number = {'0','1','2','3','4','5','6','7','8','9'}; 
       for(int i=0;i<number.length;i++)
           if(evt.getKeyChar() == number[i])
           {
               kt= true;
               break;
           }
       if(kt == false)
           evt.consume();
    }//GEN-LAST:event_txt_rgt_phoneKeyTyped

    private void bnt_rgt_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_rgt_xacnhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_rgt_xacnhanActionPerformed

    private void bntSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSuaMouseClicked
        if(this.checkInputRegister() == false)
            JOptionPane.showMessageDialog(null, "Kiểm tra lại thông tin");
        else{
            int input = JOptionPane.showConfirmDialog(null, "Bạn nuốn thay đổi thông tin?","Thông báo!",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
            if(input == JOptionPane.YES_OPTION )
            {
            this.user_chon.setPassword(this.txtpass_rgt_password.getText());
            this.user_chon.setFullname(this.txt_rgt_fullname.getText());
            this.user_chon.setAdress_user(this.txt_rgt_adress.getText());
            this.user_chon.setEmail(this.txt_rgt_email.getText());
            this.user_chon.setPhone(this.txt_rgt_phone.getText());
            
            UserController uc =new  UserController();    
            uc.UpdateUser(this.user_chon);
            JOptionPane.showMessageDialog(null, "Sủa thông tin thành công!");
            mf.setUser_sudung(user_chon);
            mf.DangNhap();
            mf.loadListPostChoThue();
            mf.loadTinCuaBan();
            this.setVisible(false);
            }   
        }
       
        
        
    }//GEN-LAST:event_bntSuaMouseClicked

    private void bntSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }
    //JTextField username,JTextField password,JTextField fullname,JTextField email,JTextField phone,JTextField adress
    public boolean checkInputRegister(){
        
        String username = txt_rgt_username.getText();
        String password = txtpass_rgt_password.getText();
        String fullname = txt_rgt_fullname.getText();
        String email    = txt_rgt_email.getText();
        String phone = txt_rgt_phone.getText();
        String adress = txt_rgt_adress.getText();
        
        
        if(username.equals("")||password.equals("")|| fullname.equals("") || email.equals("") || phone.equals("") || adress.equals(""))
            return false;
        return true;
    }
    
    public boolean checkUser(){
        String username = txt_rgt_username.getText();
        
        UserController ctr = new UserController();
        ArrayList<User> list =ctr.getUser();
        if(list.size() < 1)
            return true;
        else{
            for(int i=0;i<list.size();i++)
                if(list.get(i).getUsername().equals(username))
                    return false;
        }
        
        return true;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSua;
    private javax.swing.JButton bnt_rgt_choose_img;
    private javax.swing.JButton bnt_rgt_thoat;
    private javax.swing.JButton bnt_rgt_xacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_rgt_img;
    private javax.swing.JTextField txt_rgt_adress;
    private javax.swing.JTextField txt_rgt_email;
    private javax.swing.JTextField txt_rgt_fullname;
    private javax.swing.JTextField txt_rgt_phone;
    private javax.swing.JTextField txt_rgt_username;
    private javax.swing.JPasswordField txtpass_rgt_password;
    // End of variables declaration//GEN-END:variables
}
